# Generated by Django 3.1.1 on 2021-03-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0002_auto_20210316_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminarcustomer',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
