# Generated by Django 3.1.1 on 2021-03-16 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seminar', '0004_seminarcustomer_backup_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seminarcustomer',
            name='backup_user',
        ),
        migrations.CreateModel(
            name='BackupUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seminar_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seminar.seminarcustomer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
